# Generated by Django 5.1.6 on 2025-02-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='user',
        ),
    ]
